### ISSUE TITLE
Private database information in server.js

### ISSUE THREAD

**Issue by Cocoatwix** [axeleschholz/2315_final#1]
Lol this isn't really important since the database only has data for this specific project, but the database connection URL is in server.js, so anyone could access it and modify the stuff in there.

**Comment by axeleschholz** [comment]
Appreciate the heads up. I never intend to spin this thing up again so I just couldn't be bothered to remove the database info. I'm pretty sure I've since reset the database anyway so it's a moot point, but I'll be sure to double check so that people don't try to abuse it. Thanks again!
